language: php
php:
  - 7.0

services:
  - docker

before_install:
  - docker run -d -p 127.0.0.1:8080:80 -v `pwd`:/usr/src/app -w /usr/src/app php:7.0-apache php -S 0.0.0.0:80 -t public

script:
  - composer install
  - php vendor/bin/codecept run unit --coverage
  - php vendor/bin/codecept run functional --coverage
  - php vendor/bin/codecept run acceptance

cache:
  directories:
    - vendor
