web:
  image: nginx:1.11-alpine
  ports:
    - 8080:80
  links:
    - fpm
  volumes:
    - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
  volumes_from:
    - fpm
fpm:
  image: php:7.0-fpm
  volumes:
    - .:/var/www/html
    - /var/www/html
